{% set name = "azure-mgmt-web" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 274239993a4705c9e1135842137d77a703f63d14ee5c1a5ee87fe1f8a471a061

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.web

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Web Apps Management Client Library for Python.


extra:
  recipe-maintainers:
    - tim-werner
