{% set name = "azure-mgmt-web" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: a58750df23d5d4cb8eff283a93312e933ee3ef4272324576005c3dc8c22ce944

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - azure-common ~=1.1
    - azure-mgmt-core >=1.2.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.web

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Web Apps Management Client Library for Python.


extra:
  recipe-maintainers:
    - tim-werner
