schema_version: 1

context:
  name: azure-mgmt-web
  version: "8.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: c8d9c042c09db7aacb20270a9effed4d4e651e365af32d80897b84dc7bf35098

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - isodate >=0.6.1
    - typing-extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.web
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Web Apps Management Client Library for Python.
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
